# Generated by Django 3.2.15 on 2022-09-09 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('porto_name', models.CharField(max_length=150)),
                ('pname', models.CharField(max_length=40)),
                ('pinsta_link', models.CharField(max_length=250)),
                ('panak_ke', models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], default='1', max_length=2)),
                ('pnama_ayah', models.CharField(max_length=40)),
                ('pnama_ibu', models.CharField(max_length=40)),
                ('ppicture', models.ImageField(blank=True, upload_to='')),
                ('lname', models.CharField(max_length=40)),
                ('linsta_link', models.CharField(max_length=250)),
                ('lanak_ke', models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], default='1', max_length=2)),
                ('lnama_ayah', models.CharField(max_length=40)),
                ('lnama_ibu', models.CharField(max_length=40)),
                ('lpicture', models.ImageField(blank=True, upload_to='')),
                ('tanggal_akad', models.DateField()),
                ('waktu_akad', models.TimeField()),
                ('waktu_selesai_akad', models.TimeField()),
                ('tempat_akad', models.CharField(max_length=250)),
                ('link_gmap_akad', models.CharField(max_length=250)),
                ('tanggal_resepsi', models.DateField()),
                ('waktu_resepsi', models.TimeField()),
                ('waktu_selesai_resepsi', models.TimeField()),
                ('tempat_resepsi', models.CharField(max_length=250)),
                ('link_gmap_resepsi', models.CharField(max_length=250)),
                ('tanggal_unduhmantu', models.DateField()),
                ('waktu_unduhmantu', models.TimeField()),
                ('waktu_selesai_unduhmantu', models.TimeField()),
                ('tempat_unduhmantu', models.CharField(max_length=250)),
                ('link_gmap_unduhmantu', models.CharField(max_length=250)),
                ('video', models.CharField(max_length=250)),
                ('livestream', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('startDate', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('options', models.CharField(max_length=200)),
                ('timeZone', models.CharField(choices=[('', 'Pilih zona waktu'), ('Asia/Jakarta', 'WIB'), ('Asia/Makassar', 'WITA'), ('Asia/Jayapura', 'WIT')], max_length=30)),
                ('trigger', models.CharField(max_length=20)),
                ('iCalFileName', models.CharField(max_length=50)),
                ('link_iframe', models.TextField()),
                ('lokasi', models.CharField(max_length=250)),
                ('link_gmap', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Portofolio',
            },
        ),
        migrations.CreateModel(
            name='SpecialInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name_invite', models.CharField(max_length=100)),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio')),
            ],
            options={
                'verbose_name_plural': 'Multiimages',
            },
        ),
    ]
