# Generated by Django 3.2.15 on 2022-09-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('porto_name', models.CharField(max_length=150)),
                ('pname', models.CharField(max_length=40)),
                ('pinsta_link', models.CharField(max_length=250)),
                ('panak_ke', models.IntegerField(default=1)),
                ('pnama_ayah', models.CharField(max_length=40)),
                ('pnama_ibu', models.CharField(max_length=40)),
                ('ppicture', models.ImageField(blank=True, upload_to='')),
                ('lname', models.CharField(max_length=40)),
                ('linsta_link', models.CharField(max_length=250)),
                ('lanak_ke', models.IntegerField(default=1)),
                ('lnama_ayah', models.CharField(max_length=40)),
                ('lnama_ibu', models.CharField(max_length=40)),
                ('lpicture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Portofolio',
            },
        ),
    ]
