# Generated by Django 3.2.15 on 2022-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('tanggal_akad', models.DateField()),
                ('tanggal_selesai_akad', models.DateField()),
                ('tempat_akad', models.CharField(max_length=250)),
                ('link_gmap_akad', models.CharField(max_length=250)),
                ('tanggal_resepsi', models.DateField()),
                ('tanggal_selesai_resepsi', models.DateField()),
                ('tempat_resepsi', models.CharField(max_length=250)),
                ('link_gmap_resepsi', models.CharField(max_length=250)),
                ('tanggal_unduhmantu', models.DateField()),
                ('tanggal_selesai_unduhmantu', models.DateField()),
                ('tempat_unduhmantu', models.CharField(max_length=250)),
                ('link_gmap_unduhmantu', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddtoCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('startDate', models.DateField()),
                ('location', models.CharField(max_length=250)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('options', models.CharField(max_length=250)),
                ('timeZone', models.CharField(max_length=250)),
                ('trigger', models.CharField(max_length=250)),
                ('iCalFileName', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('pname', models.CharField(max_length=40)),
                ('pinsta_link', models.CharField(max_length=250)),
                ('panak_ke', models.IntegerField()),
                ('pnama_ayah', models.CharField(max_length=40)),
                ('pnama_ibu', models.CharField(max_length=40)),
                ('ppicture', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('linsta_link', models.CharField(max_length=250)),
                ('lanak_ke', models.IntegerField()),
                ('lnama_ayah', models.CharField(max_length=40)),
                ('lnama_ibu', models.CharField(max_length=40)),
                ('lpicture', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dompet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('rekening', models.CharField(max_length=40)),
                ('nomor', models.IntegerField()),
                ('pemilik', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('link_iframe', models.CharField(max_length=250)),
                ('lokasi', models.CharField(max_length=250)),
                ('link_gmap', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hadir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=40)),
                ('hadir', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ourmoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('video', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=250)),
                ('livestream', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('ayat', models.CharField(max_length=250)),
                ('kutipan', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ucapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=40)),
                ('alamat', models.CharField(max_length=40)),
                ('pesan', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
