# Generated by Django 3.2.15 on 2022-08-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acara',
            options={'verbose_name_plural': 'Acara'},
        ),
        migrations.AlterModelOptions(
            name='addtocalender',
            options={'verbose_name_plural': 'AddtoCalender'},
        ),
        migrations.AlterModelOptions(
            name='couple',
            options={'verbose_name_plural': 'Couple'},
        ),
        migrations.AlterModelOptions(
            name='dompet',
            options={'verbose_name_plural': 'Dompet'},
        ),
        migrations.AlterModelOptions(
            name='goto',
            options={'verbose_name_plural': 'Goto'},
        ),
        migrations.AlterModelOptions(
            name='hadir',
            options={'verbose_name_plural': 'Hadir'},
        ),
        migrations.AlterModelOptions(
            name='ourmoment',
            options={'verbose_name_plural': 'Ourmoment'},
        ),
        migrations.AlterModelOptions(
            name='quotes',
            options={'verbose_name_plural': 'Quotes'},
        ),
        migrations.AlterModelOptions(
            name='specialinvitation',
            options={'verbose_name_plural': 'SpecialInvitation'},
        ),
        migrations.AlterModelOptions(
            name='ucapan',
            options={'verbose_name_plural': 'Ucapan'},
        ),
    ]
