# Generated by Django 3.2.15 on 2022-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='link_gmap_akad',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='link_gmap_resepsi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='link_gmap_unduhmantu',
            field=models.TextField(),
        ),
    ]
