# Generated by Django 3.2.15 on 2022-09-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_change_field_to_link_maps_akad_resepsi_unduhmantu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dompet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('nomor', models.IntegerField()),
                ('pemilik', models.CharField(max_length=40)),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio')),
            ],
            options={
                'verbose_name_plural': 'Dompet',
            },
        ),
    ]
