# Generated by Django 3.2.15 on 2022-09-06 01:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_change_panake_ke_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='link_gmap_akad',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='link_gmap_resepsi',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='link_gmap_unduhmantu',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_akad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 48, 50, 653193, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_resepsi',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 49, 0, 260991, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_selesai_akad',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 49, 11, 38009, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_selesai_resepsi',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 49, 17, 94763, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_selesai_unduhmantu',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 49, 21, 391125, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_unduhmantu',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 1, 49, 32, 742042, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tempat_akad',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tempat_resepsi',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='tempat_unduhmantu',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='lanak_ke',
            field=models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='panak_ke',
            field=models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], default='1', max_length=2),
        ),
    ]
