# Generated by Django 3.2.15 on 2022-08-27 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_auto_20220827_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couple',
            name='pname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=250)),
                ('acara', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portofolio.acara')),
                ('addtocalender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portofolio.addtocalender')),
                ('couple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portofolio.couple')),
                ('dompet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.dompet')),
                ('goto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portofolio.goto')),
                ('hadir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.hadir')),
                ('ourmoment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.ourmoment')),
                ('quotes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portofolio.quotes')),
                ('specialinvitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.specialinvitation')),
                ('ucapan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.ucapan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
