# Generated by Django 3.2.15 on 2022-09-06 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0003_add_model_acara'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='waktu_akad',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 2, 59, 44, 985569, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_akad',
            field=models.DateField(),
        ),
    ]
