# Generated by Django 3.2.15 on 2022-09-06 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_add_timefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='waktu_resepsi',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 3, 50, 39, 41528, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='waktu_selesai_akad',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 3, 50, 45, 450319, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='waktu_selesai_resepsi',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 3, 50, 51, 789157, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='waktu_selesai_unduhmantu',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 3, 50, 56, 501187, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='waktu_unduhmantu',
            field=models.TimeField(default=datetime.datetime(2022, 9, 6, 3, 50, 59, 701158, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_resepsi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_selesai_akad',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_selesai_resepsi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_selesai_unduhmantu',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='tanggal_unduhmantu',
            field=models.DateField(),
        ),
    ]
