# Generated by Django 3.2.15 on 2022-08-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0004_portofolio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='acara',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='addtocalender',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='couple',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='dompet',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='goto',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='hadir',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='ourmoment',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='quotes',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='specialinvitation',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='ucapan',
        ),
        migrations.AddField(
            model_name='acara',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='addtocalender',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='couple',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='dompet',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='goto',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='hadir',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='ourmoment',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='specialinvitation',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
        migrations.AddField(
            model_name='ucapan',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
    ]
