# Generated by Django 3.2.15 on 2022-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_add_rekening_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dompet',
            name='rekening',
            field=models.CharField(choices=[('', 'Pilih bank'), ('BANK RAKYAT INDONESIA', 'BANK RAKYAT INDONESIA'), ('BANK NEGARA INDONESIA', 'BANK NEGARA INDONESIA'), ('MANDIRI', 'MANDIRI')], max_length=40),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='lanak_ke',
            field=models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], max_length=2),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='panak_ke',
            field=models.CharField(choices=[('1', 'Pertama'), ('2', 'Kedua'), ('3', 'Ketiga'), ('4', 'Keempat'), ('5', 'Kelima'), ('6', 'Keenam'), ('7', 'Ketujuh'), ('8', 'Kedelapan'), ('9', 'Kesembilan')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Rekening',
        ),
    ]
