# Generated by Django 3.2.15 on 2022-09-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_add_timefield_for_akad_resepsi_unduhmantu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='tanggal_selesai_akad',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tanggal_selesai_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tanggal_selesai_unduhmantu',
        ),
    ]
