# Generated by Django 3.2.15 on 2022-08-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0005_auto_20220828_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portofolio',
            options={'verbose_name_plural': 'Portofolio'},
        ),
        migrations.AlterField(
            model_name='hadir',
            name='hadir',
            field=models.CharField(choices=[('iya', 'iya'), ('tidak', 'tidak')], default='tidak', max_length=20),
        ),
    ]
