# Generated by Django 3.2.15 on 2022-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_choice_di_hadir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocalender',
            name='timeZone',
            field=models.CharField(choices=[('Asia/Jakarta', 'Asia/Jakarta'), ('Asia/Makassar', 'Asia/Makassar'), ('Asia/Jayapura', 'Asia/Jayapura')], default='Asia/Jakarta', max_length=20),
        ),
    ]
