# Generated by Django 3.2.15 on 2022-09-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_delete_rekening_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('ayat', models.CharField(max_length=250)),
                ('kutipan', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Quotes',
            },
        ),
        migrations.AddField(
            model_name='portofolio',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.quote'),
        ),
    ]
