# Generated by Django 3.2.15 on 2022-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0006_delete_tanggal_selesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='livestream',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='video',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
