# Generated by Django 3.2.15 on 2022-09-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0007_add_quote_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
    ]
