# Generated by Django 3.2.15 on 2022-09-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0007_add_video_and_livestream_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='photos',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
