# Generated by Django 3.2.15 on 2022-08-28 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0008_add_picture_database'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='PhotoOurmoment',
        ),
        migrations.RemoveField(
            model_name='ourmoment',
            name='photo',
        ),
    ]
