# Generated by Django 3.2.15 on 2022-09-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0008_add_multiple_photos_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Multiimages',
            },
        ),
    ]
