# Generated by Django 3.2.15 on 2022-09-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0009_create_model_class_multiimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='portofolio.multiimage'),
        ),
    ]
