# Generated by Django 3.2.15 on 2022-09-06 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_create_model_foreignkey_for_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='photos',
        ),
        migrations.AddField(
            model_name='multiimage',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
    ]
