# Generated by Django 3.2.15 on 2022-09-22 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0010_add_ucapan_and_hadir_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dompet',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='hadir',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='multiimage',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='specialinvitation',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='ucapan',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
    ]
