# Generated by Django 3.2.15 on 2022-09-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portofolio', '0011_create_allauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='slug',
            field=models.SlugField(default='jono', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='user',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
