# Generated by Django 3.2.15 on 2022-09-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0011_edit_multiimage_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
