# Generated by Django 3.2.15 on 2022-09-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0012_create_user_and_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
