# Generated by Django 3.2.15 on 2022-09-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0012_add_id_auto_field_portofolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
