# Generated by Django 3.2.15 on 2022-09-23 08:52

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0013_add_paid_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=255)),
                ('price', models.FloatField()),
                ('fitur', multiselectfield.db.fields.MultiSelectField(choices=[('preset standard', 'preset standard'), ('quotes', 'quotes'), ('detail acara', 'detail acara'), ('profil pasangan', 'profil pasangan'), ('protokol kesehatan', 'protokol kesehatan'), ('navigasi lokasi', 'navigasi lokasi'), ('google calender', 'google calender'), ('unlimited custom jadwal acara', 'unlimited custom jadwal acara'), ('rsvp', 'rsvp'), ('amplop digital', 'amplop digital'), ('kirim ucapan', 'kirim ucapan'), ('gallery(max 10)', 'gallery(max 10)'), ('love stories', 'love stories'), ('buku tamu', 'buku tamu'), ('share eksklusif(max 50)', 'share eksklusif(max 50)'), ('background music(list only)', 'background music(list only)'), ('custom domain(additional)', 'custom domain(additional)'), ('preset platinum', 'preset platinum'), ('gallery(max 20)', 'gallery(max 20)'), ('live streaming', 'live streaming'), ('share eksklusif(unlimited)', 'share eksklusif(unlimited)'), ('background music(list dan custom)', 'background music(list dan custom)'), ('tersedia versi inggris', 'tersedia versi inggris'), ('semua jenis preset', 'semua jenis preset'), ('support prioritas', 'support prioritas'), ('masa aktif selamanya', 'masa aktif selamanya'), ('edit tanpa batas', 'edit tanpa batas')], max_length=488)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='paid',
        ),
    ]
