# Generated by Django 3.2.15 on 2022-09-06 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0013_delete_id_auto_field_portofolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='name_invite',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=[], size=None),
            preserve_default=False,
        ),
    ]
