# Generated by Django 3.2.15 on 2022-09-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0014_name_invit_array_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='name_invite',
            field=models.CharField(max_length=250),
        ),
    ]
