# Generated by Django 3.2.15 on 2022-09-07 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0015_delete_name_invit_array_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portofolio',
            name='name_invite',
        ),
        migrations.CreateModel(
            name='SpecialInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name_invite', models.CharField(max_length=100)),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
