# Generated by Django 3.2.15 on 2022-09-08 13:44

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0016_add_special_invitation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 13, 43, 38, 660747, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='iCalFileName',
            field=models.CharField(default='Reminder-Event', max_length=50),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='location',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='name',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=['Google', 'Apple', 'iCal', 'Yahoo', 'Outlook.com', 'Microsoft365'], max_length=200), default=[''], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 8, 13, 44, 16, 95283, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2022, 9, 8, 13, 44, 27, 278309, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portofolio',
            name='timeZone',
            field=models.CharField(choices=[('Asia/Jakarta', 'Asia/Jakarta'), ('Asia/Makassar', 'Asia/Makassar'), ('Asia/Jayapura', 'Asia/Jayapura')], default='Asia/Jakarta', max_length=30),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='trigger',
            field=models.CharField(default='click', max_length=20),
        ),
    ]
