# Generated by Django 3.2.15 on 2022-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0018_add_fiturproduct_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portofolio',
            options={'verbose_name_plural': 'APortofolio'},
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='porto_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
