# Generated by Django 3.2.15 on 2022-10-06 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0019_make_porto_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='datetime_akad',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 8, 51, 49, 852505, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
