# Generated by Django 3.2.15 on 2022-10-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0020_add_datetime_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portofolio',
            old_name='datetime_akad',
            new_name='datetime_resepsi',
        ),
    ]
