# Generated by Django 3.2.15 on 2022-10-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0022_datetime_resepsi_to_caharfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='lanak_ke',
            field=models.CharField(choices=[('Pertama', 'Pertama'), ('Kedua', 'Kedua'), ('Ketiga', 'Ketiga'), ('Keempat', 'Keempat'), ('Kelima', 'Kelima'), ('Keenam', 'Keenam'), ('Ketujuh', 'Ketujuh'), ('Kedelapan', 'Kedelapan'), ('Kesembilan', 'Kesembilan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='panak_ke',
            field=models.CharField(choices=[('Pertama', 'Pertama'), ('Kedua', 'Kedua'), ('Ketiga', 'Ketiga'), ('Keempat', 'Keempat'), ('Kelima', 'Kelima'), ('Keenam', 'Keenam'), ('Ketujuh', 'Ketujuh'), ('Kedelapan', 'Kedelapan'), ('Kesembilan', 'Kesembilan')], max_length=30),
        ),
    ]
