# Generated by Django 3.2.15 on 2022-10-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0023_edit_charfield_length_for_anak_ke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='livestream',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='video',
            field=models.TextField(),
        ),
    ]
