# Generated by Django 3.2.15 on 2022-10-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0024_change_video_and_livestreamField'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('fitur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.fitur')),
                ('portofolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='theme',
            name='fitur',
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FiturProduct',
        ),
        migrations.AddField(
            model_name='themeproduct',
            name='theme',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.theme'),
        ),
    ]
