# Generated by Django 3.2.15 on 2022-10-09 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0025_add_theme_change_themeproduct_and_delete_fiturproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='portofolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
        migrations.AlterField(
            model_name='themeproduct',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.theme'),
        ),
    ]
