# Generated by Django 3.2.15 on 2022-10-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0026_change_foreign_key_to_themeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.portofolio'),
        ),
    ]
