# Generated by Django 3.2.15 on 2022-11-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0028_add_kabupaten_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('year', models.CharField(max_length=5)),
                ('cerita', models.TextField()),
                ('image', models.FileField(blank=True, upload_to='')),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
