# Generated by Django 3.2.15 on 2022-11-05 17:44

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0029_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='lpicture_resize',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[180, 180], upload_to='whatever'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='themeproduct',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
        ),
    ]
