# Generated by Django 3.2.15 on 2022-11-05 17:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0031_edit_pic_resize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=-1, scale=0.5, size=[180, 180], upload_to='whatever'),
        ),
    ]
