# Generated by Django 3.2.15 on 2022-11-06 14:40

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0032_edit_pic_resize'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='cover_background',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='lpicture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=100, scale=1, size=[180, 180], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=100, scale=1, size=[180, 180], upload_to='whatever'),
        ),
    ]
