# Generated by Django 3.2.15 on 2022-11-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0034_add_fitur_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='line',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='open_fitur',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='rundown_fitur',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='space',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
