# Generated by Django 3.2.15 on 2022-11-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0035_add_other_theme_fitur_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='linsta_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='pinsta_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
