# Generated by Django 3.2.15 on 2022-11-18 08:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0037_pinsta_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='panak_ke',
            field=models.CharField(blank=True, choices=[('Pertama', 'Pertama'), ('Kedua', 'Kedua'), ('Ketiga', 'Ketiga'), ('Keempat', 'Keempat'), ('Kelima', 'Kelima'), ('Keenam', 'Keenam'), ('Ketujuh', 'Ketujuh'), ('Kedelapan', 'Kedelapan'), ('Kesembilan', 'Kesembilan')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='pinsta_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='pnama_ayah',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='pnama_ibu',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='pname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='porto_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[180, 180], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
