# Generated by Django 3.2.15 on 2022-11-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0039_default_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('tanggal_acara', models.DateField(blank=True, null=True)),
                ('waktu_mulai_acara', models.TimeField(blank=True, null=True)),
                ('waktu_selesai_acara', models.TimeField(blank=True, null=True)),
                ('tempat_acara', models.CharField(blank=True, max_length=250, null=True)),
                ('link_gmap_acara', models.TextField(blank=True, null=True)),
                ('portofolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
