# Generated by Django 3.2.15 on 2022-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0040_create_formset_acara'),
    ]

    operations = [
        migrations.AddField(
            model_name='acara',
            name='nama_acara',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
