# Generated by Django 3.2.15 on 2022-11-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0041_create_formset_acara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portofolio',
            old_name='datetime_resepsi',
            new_name='datetime_countdown',
        ),
        migrations.RenameField(
            model_name='portofolio',
            old_name='tanggal_akad',
            new_name='tanggal_countdown',
        ),
        migrations.RenameField(
            model_name='portofolio',
            old_name='waktu_akad',
            new_name='waktu_countdown',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='link_gmap_akad',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='link_gmap_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='link_gmap_unduhmantu',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tanggal_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tanggal_unduhmantu',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tempat_akad',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tempat_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='tempat_unduhmantu',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='waktu_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='waktu_selesai_akad',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='waktu_selesai_resepsi',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='waktu_selesai_unduhmantu',
        ),
        migrations.RemoveField(
            model_name='portofolio',
            name='waktu_unduhmantu',
        ),
    ]
