# Generated by Django 3.2.15 on 2022-11-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0043_edit_portofolio_model_acara'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='tanggal_akad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
