# Generated by Django 3.2.15 on 2022-11-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0045_delete_tanggal_akad'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='kata_live_streaming',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='kata_moment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='kata_special_invite',
            field=models.TextField(blank=True, null=True),
        ),
    ]
