# Generated by Django 3.2.15 on 2022-11-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0046_add_kata_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='portofolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portofolio.portofolio'),
        ),
    ]
