# Generated by Django 3.2.15 on 2022-11-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0048_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='link_gmap_acara',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
