# Generated by Django 3.2.15 on 2022-11-27 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0050_url_field_livestream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dompet',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hadir',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='multiimage',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialinvitation',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='themeproduct',
            name='portofolio',
            field=models.OneToOneField(default=28, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portofolio.portofolio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ucapan',
            name='portofolio',
            field=models.ForeignKey(default=28, on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio'),
            preserve_default=False,
        ),
    ]
