# Generated by Django 3.2.15 on 2022-11-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0052_change_ayat_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='ayat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
