# Generated by Django 3.2.15 on 2022-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0053_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='open_background',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
