# Generated by Django 3.2.15 on 2022-12-12 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0054_add_cover_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeproduct',
            name='fitur',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
