# Generated by Django 3.2.15 on 2022-12-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0056_edit_music_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.CharField(default='akad', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
