# Generated by Django 3.2.15 on 2022-12-16 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0057_edit_music_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('pembuka', models.TextField(blank=True, null=True)),
                ('isi', models.TextField(blank=True, null=True)),
                ('penutup', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
