# Generated by Django 3.2.15 on 2022-12-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0058_add_kata_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='ornament_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='ornament_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='ornament_3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='ornament_4',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
