# Generated by Django 3.2.15 on 2022-12-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0060_add_background_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='background_5',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='background_cover',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='theme',
            name='background_open',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
