# Generated by Django 3.2.15 on 2022-12-24 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0061_add_cover_and_open_background_in_theme_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='fitur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.fitur'),
        ),
        migrations.AddField(
            model_name='theme',
            name='pembuat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='theme_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
