# Generated by Django 3.2.15 on 2022-12-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0062_add_theme_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='preview_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
