# Generated by Django 3.2.15 on 2022-12-29 08:56

from django.db import migrations, models
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0063_add_new_url_preview_to_theme_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.portofolio_multiimage_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='cover_background',
            field=models.ImageField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.portofolio_background_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='lpicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[180, 180], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='open_background',
            field=models.ImageField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.portofolio_background_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=100, scale=1, size=[180, 180], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.portofolio_story_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_1',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_2',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_3',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_4',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_5',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_cover',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_open',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cover_fitur',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='line',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='open_fitur',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ornament_1',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ornament_2',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ornament_3',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='ornament_4',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='quote_fitur',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='rundown_fitur',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='space',
            field=models.FileField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_picture',
            field=models.ImageField(blank=True, null=True, upload_to=myproject.apps.portofolio.models.theme_upload_to),
        ),
    ]
