# Generated by Django 3.2.15 on 2022-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0064_auto_20221229_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='porto_name',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
    ]
