# Generated by Django 3.2.15 on 2022-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0065_add_max_num_for_porto_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pembuka',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='description',
            field=models.TextField(blank=True, default='Merupakan undangan pernikahan kami. Besar harapan untuk kehadiran bapak/ibu, dan atas perhatianya diucapkan terimakasih', null=True),
        ),
    ]
