# Generated by Django 3.2.15 on 2022-12-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0066_add_pembuka_to_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.track'),
        ),
    ]
