# Generated by Django 3.2.15 on 2022-12-30 07:40

from django.db import migrations, models
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0067_track_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimage',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=myproject.apps.portofolio.models.portofolio_multiimage_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='cover_background',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=myproject.apps.portofolio.models.portofolio_background_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='lpicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=100, scale=1, size=[180, 180], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='open_background',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=myproject.apps.portofolio.models.portofolio_background_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=100, scale=1, size=[180, 180], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=myproject.apps.portofolio.models.portofolio_story_upload_to),
        ),
    ]
