# Generated by Django 3.2.15 on 2023-02-02 06:37

from django.db import migrations
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0072_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='lpicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=100, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
        migrations.AlterField(
            model_name='portofolio',
            name='ppicture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=100, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_pasangan_upload_to),
        ),
    ]
