# Generated by Django 3.2.15 on 2023-02-09 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0074_add_alamat_dan_barcode_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('nama', models.CharField(blank=True, max_length=250, null=True)),
                ('jumlah', models.CharField(blank=True, max_length=40, null=True)),
                ('pesan', models.CharField(blank=True, max_length=500, null=True)),
                ('ditransfer_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.dompet')),
                ('portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
