# Generated by Django 3.2.15 on 2023-02-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0075_add_new_model_for_dana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dana',
            name='ditransfer_ke',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
