# Generated by Django 3.2.15 on 2023-02-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0076_add_new_model_for_dana_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='lsurename',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='portofolio',
            name='psurename',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
