# Generated by Django 3.2.15 on 2023-03-13 15:21

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0077_auto_20230220_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('quantity_porto', models.IntegerField(blank=True, default=13, null=True)),
                ('quantity_ucapan', models.IntegerField(blank=True, default=8, null=True)),
                ('quantity_dompet', models.IntegerField(blank=True, default=25, null=True)),
                ('quantity_tamu', models.IntegerField(blank=True, default=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fitur',
            name='fitur',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('desain standard', 'desain standard'), ('quotes', 'quotes'), ('detail acara', 'detail acara'), ('profil pasangan', 'profil pasangan'), ('protokol kesehatan', 'protokol kesehatan'), ('navigasi lokasi', 'navigasi lokasi'), ('google calender', 'google calender'), ('custom jadwal acara', 'custom jadwal acara'), ('kirim ucapan', 'kirim ucapan'), ('rsvp', 'rsvp'), ('amplop digital', 'amplop digital'), ('gallery(max 10)', 'gallery(max 10)'), ('gallery(max 5)', 'gallery(max 5)'), ('love stories', 'love stories'), ('buku tamu', 'buku tamu'), ('background music(list only)', 'background music(list only)'), ('custom domain(additional)', 'custom domain(additional)'), ('share eksklusif(unlimited)', 'share eksklusif(unlimited)'), ('desain platinum', 'desain platinum'), ('background music(list dan custom)', 'background music(list dan custom)'), ('gallery(max 20)', 'gallery(max 20)'), ('live streaming', 'live streaming'), ('tersedia versi inggris', 'tersedia versi inggris'), ('semua jenis desain', 'semua jenis desain'), ('terima beres dibuatkan admin', 'terima beres dibuatkan admin'), ('custom color & font', 'custom color & font'), ('request custom design', 'request custom design'), ('support prioritas', 'support prioritas'), ('edit tanpa batas', 'edit tanpa batas')], max_length=519, null=True),
        ),
    ]
