# Generated by Django 3.2.15 on 2023-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0078_create_resume_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='nama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
