# Generated by Django 3.2.15 on 2023-06-28 11:54

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0079_create_resume_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='quantity_dompet',
            field=models.IntegerField(blank=True, default=26, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='quantity_porto',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='quantity_tamu',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='quantity_ucapan',
            field=models.IntegerField(blank=True, default=27, null=True),
        ),
        migrations.CreateModel(
            name='MultiImageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimage_upload_to)),
                ('portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'verbose_name_plural': 'MultiImageThemes',
            },
        ),
    ]
