# Generated by Django 3.2.15 on 2023-06-30 07:56

from django.db import migrations
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0080_auto_20230628_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiimagetheme',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to),
        ),
    ]
