# Generated by Django 3.2.15 on 2023-07-08 16:23

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import myproject.apps.portofolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0081_alter_multiimagetheme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='quantity_tamu',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.CreateModel(
            name='PortoBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image3', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image4', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image5', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image6', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image7', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image8', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image9', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('image10', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, max_length=500, null=True, quality=75, scale=1, size=[1920, 1080], upload_to=myproject.apps.portofolio.models.portofolio_multiimagetheme_upload_to)),
                ('portofolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portofolio.portofolio')),
            ],
            options={
                'verbose_name_plural': 'ThemeBackgrounds',
            },
        ),
    ]
