# Generated by Django 3.2.15 on 2023-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropping', '0001_add_new_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='file2',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
