# Generated by Django 3.2.15 on 2023-01-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropping', '0002_add_new_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('file2', models.ImageField(upload_to='')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'photo2',
                'verbose_name_plural': 'photos2',
            },
        ),
    ]
