# Generated by Django 3.2.15 on 2022-11-10 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0035_add_other_theme_fitur_field'),
        ('coupon', '0001_create_coupon_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='fitur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portofolio.fitur'),
        ),
    ]
