# Generated by Django 3.2.15 on 2022-11-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_add_fitur_field_in_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='fitur',
        ),
        migrations.AddField(
            model_name='coupon',
            name='gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='platinum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='silver',
            field=models.BooleanField(default=False),
        ),
    ]
