# Generated by Django 3.2.15 on 2023-03-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_delete_fitur_field_in_coupon_and_add_boolean_for_fiture'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='diamond',
            field=models.BooleanField(default=False),
        ),
    ]
