# Generated by Django 3.2.15 on 2022-09-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0018_add_fiturproduct_model'),
        ('order', '0001_add_order_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fitur',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.fitur')),
            ],
        ),
    ]
