# Generated by Django 3.2.15 on 2022-09-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0018_add_fiturproduct_model'),
        ('order', '0002_add_orderitem_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.fitur'),
        ),
    ]
