# Generated by Django 3.2.15 on 2022-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_add_payment_and_nama_rekening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(default='joni', max_length=100),
            preserve_default=False,
        ),
    ]
