# Generated by Django 3.2.15 on 2022-09-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_change_order_user_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.FloatField(default=0.0),
        ),
    ]
