# Generated by Django 3.2.15 on 2022-10-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0028_add_kabupaten_field'),
        ('order', '0010_change_user_field_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portofolio.kabupaten'),
        ),
    ]
