# Generated by Django 3.2.15 on 2022-12-12 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0055_change_themeproduct_model'),
        ('order', '0012_add_field_to_order_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_update',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='portofolio.fitur'),
        ),
    ]
