# Generated by Django 3.2.15 on 2022-12-29 08:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import myproject.apps.order.models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0064_auto_20221229_1556'),
        ('order', '0013_add_field_to_order_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bukti',
            field=models.ImageField(blank=True, null=True, upload_to=myproject.apps.order.models.order_bukti_upload_to),
        ),
        migrations.AlterField(
            model_name='order',
            name='bukti_upgrade',
            field=models.ImageField(blank=True, null=True, upload_to=myproject.apps.order.models.order_bukti_upgrade_upload_to),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='portofolio.fitur'),
        ),
    ]
